name: build-sforwarder
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'

    - name: Build sforwarder
      run: cd sforwarder && make amd64 && ./build/linux-amd64/sforwarder -V
