name: build-sforwarder
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'

    - name: Install build tools
      run: sudo apt update && sudo apt install -y lsb-release build-essential debhelper

    - name: Build sforwarder for amd64
      run: cd sforwarder && make amd64

    - name: Run amd64 sforwarder
      run: ./sforwarder/build/linux-amd64/sforwarder -V

    - name: Package sforwarder for amd64
      run: cd sforwarder && dpkg-buildpackage --host-arch amd64 -b --no-sign

    - name: Install sforwarder for amd64
      run: sudo dpkg -i mote-sforwarder_*_amd64.deb

    - name: Run installed sforwarder
      run: sforwarder -V
