name: build-sforwarder
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'

    - name: Install build tools
      run: sudo apt update && sudo apt install -y lsb-release build-essential debhelper


    # AMD64
    - name: Build sforwarder for amd64
      run: cd sforwarder && make amd64

    - name: Run amd64 sforwarder
      run: ./sforwarder/build/linux-amd64/sforwarder -V

    - name: Package sforwarder for amd64
      run: cd sforwarder && dpkg-buildpackage --host-arch amd64 -b --no-sign

    - name: Install sforwarder for amd64
      run: sudo dpkg -i mote-sforwarder_*_amd64.deb

    - name: Run installed sforwarder
      run: sforwarder -V


    # ARMv5 / armel
    - name: Build sforwarder for arm5 and name it armel
      run: cd sforwarder && make arm5 && mv build/linux-arm5 build/linux-armel

    - name: Package sforwarder for armel
      run: cd sforwarder && dpkg-buildpackage --host-arch armel -b --no-sign


    # ARMv6 / armhf
    - name: Build sforwarder for arm6 and name it armhf
      run: cd sforwarder && make arm6 && mv build/linux-arm6 build/linux-armhf

    - name: Package sforwarder for armhf
      run: cd sforwarder && dpkg-buildpackage --host-arch armhf -b --no-sign


    # Publish
    - uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: "mote-sforwarder*.deb"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
